<?php


use App\Services\BudgetService;
use Carbon\Carbon;
use PHPUnit\Framework\TestCase;

class BTest extends TestCase
{
    /**
     * @var \Illuminate\Contracts\Foundation\Application|mixed
     */
    private  $service;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->service = new BudgetService(new \App\Services\BudgetRepo());
    }

    public function test_start_less_than_end()
    {
        $end = Carbon::parse('2022-10-01');
        $start= Carbon::parse('2022-10-30');

        $result = $this->service->query($start, $end);

        $this->assertEquals(0, $result);

   }

   public function test_get_current_month_amount()
   {
       $start = Carbon::parse('2022-10-01');
       $end = Carbon::parse('2022-10-31');

       $result = $this->service->query($start, $end);

       $this->assertEquals([
           [
               'year_month' => '202210',
               'amount' => 3100
           ]
       ], $result);
   }

    public function test_get_budget_between_two_date()
    {
        $start = Carbon::parse('2022-10-31'); //96.7741935
        $end = Carbon::parse('2022-11-01'); //100

        $result = $this->service->query($start, $end);

        $this->assertEquals(196.77, $result);
    }

}
